name: Deploy to GAE

# Controls when the workflow will run
on:
  push:
    branches: [master]

  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel

# This Job runs for developer mode
jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 18.12.1
    - name: Listing
      run: ls
    - name: Check NPM version
      run: npm --version
    - name: Check Node version
      run: node --version
    - name: Building frontend
      run: |
          ls
          npm install --force
          CI= npm run build
    - name: Deploy to App Engine
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: app.yaml
        version: v1
        project_id: ${{ secrets.PROJECT_ID }}
        credentials: ${{ secrets.SERVICE_ACCOUNT }}